---
- name: Install Minecraft
  hosts: minecraft
  vars:
    user:
      username: minecraft
    minecraft:
      dest: /opt/minecraft
      url: https://launcher.mojang.com/mc/game/1.12.2/server/886945bfb2b978778c3a0288fd7fab09d315b25f/server.jar
      memory: 1024

  handlers:
    - name: restart minecraft
      become: yes
      systemd:
        name: minecraft
        state: restarted
        daemon_reload: yes
        enabled: yes

  tasks:
    - name: Install java
      become: yes
      yum: name=java state=installed

    - name: mkdir {{minecraft.dest}}
      become: yes
      file: dest={{minecraft.dest}} state=directory owner={{user.username}} group={{user.username}} mode=755

    - name: download minecraft server jar
      get_url: url={{minecraft.url}} dest={{minecraft.dest}}

    - name: put eula
      copy: src=eula.txt dest={{minecraft.dest}}

    - name: put run.sh
      template: src=run.sh.j2 dest={{minecraft.dest}}/run.sh mode=a+x
      notify: restart minecraft

    - name: put minecraft.service
      become: yes
      template: src=minecraft.service.j2 dest=/etc/systemd/system/minecraft.service
      notify: restart minecraft

    - name: symlink
      become: yes
      file:
        src:  /etc/systemd/system/minecraft.service
        dest: /etc/systemd/system/multi-user.target.wants/minecraft.service
        state: link
      notify: restart minecraft
