---
- name: Install Minecraft
  hosts: minecraft
  vars:
    minecraft:
      dest: /opt/minecraft
      memory: 1024

  handlers:
    - name: restart minecraft
      become: yes
      systemd:
        name: minecraft
        state: restarted
        enabled: yes

  tasks:
    - name: put run.sh
      template: src=run.sh.j2 dest={{minecraft.dest}}/run.sh mode=a+x

    - name: rewrite server.propaties
      template: src=server.properties.j2 dest={{minecraft.dest}}/server.properties
      notify: restart minecraft
